data:
  base_dir: "data\\programs"
  org_video_dir: "org_video"        
  extracted_scenes_dir: "scenes"      
  cropped_video_dir: "cropped_video"  
  program_to_extract: "2001345"
# - data
#   - programs
#     - program_A
#       - episode 1
#         - org_video --> original mp4 or gzip frames
#         - scenes
#          - scene_0  --> gziped cropped frames for scene 0
#          - scene_1  --> gziped cropped frames for scene 0
#     - program_B
#       - ...
#     - ...

scene_extraction:
  subtitle_time_threshold: 4
  YOLO_model: yolo11s.pt
  tracking_model: bytetrack.yaml

cloud_services:
  aurora_stuff: "aurora-stuff"
  Rook_Ceph_bucket_name: "rok-ceph-bucket"
  Rook_Ceph_access_key: "rok-ceph-access-key"
  Rook_Ceph_secret_key: "rok-ceph-secret-key"
  storage_settings: "storage-settings"
  

masking:
  mask_ratio: 0.05

scene_detection:
  threshold: 0.05
